PROJECT_NAME=ictsh
PROJECT_HOME=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_SRC=${PROJECT_HOME}/data/source
PROJECT_INTAKE=${PROJECT_HOME}/data/intake
PROJECT_TEMP=${PROJECT_HOME}/temp
PROJECT_RUN=${PROJECT_HOME}/run
PROJECT_LOG=${PROJECT_HOME}/log
DB_USER=ictsh
